# Intelligent Plant Care Recommendation System 🌱

## Step 1: Import Required Libraries

In this section, we import the Python libraries required for handling data and building our plant care system.

In [4]:
import pandas as pd
import numpy as np
import json

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 1: Load the Plant Dataset

In this section, we load the Plantfolio plant dataset.

The dataset contains information about a large number of plant species, including their care requirements and characteristics.

In [5]:
file_path = r"C:/Users/mangl/OneDrive/Desktop/Plant care system/data/common_plants.json"

with open(file_path, "r", encoding="utf-8") as file:
    plant_data = json.load(file)

print("Dataset loaded successfully!")

Dataset loaded successfully!

## Step 3: Import Machine Learning Libraries

We import the tools required for text processing, model training, and saving the trained model.

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib

print("Machine Learning libraries imported successfully!")

Machine Learning libraries imported successfully!

## Step 2: Inspect the Dataset Structure

Before processing the dataset, we inspect its structure to understand how the plant information is stored.

In [3]:
print(type(plant_data))
print("Total records:", len(plant_data))

<class 'list'>
Total records: 953

## Step 3: Examine a Plant Record

We examine one plant entry to understand the available information and column structure.

In [4]:
print(plant_data[1])

{'id': 'aglaonema', 'typeName': 'Aglaonema', 'description': 'Also known as: Chinese evergreen. Low-light tolerant aroids with variegated foliage in shades of green, silver, pink, or red.', 'commonExamples': "Aglaonema commutatum (Chinese evergreen), A. pictum, A. 'Silver Bay', A. 'Maria', A. 'Red Siam', A. 'Pink Star'", 'careTips': 'Water when top 1-2 inches of soil feels dry. Keep slightly more moist than other low-light plants but avoid soggy soil. Bright indirect light maintains variegation; low light is tolerated but may reduce color. Maintain 50-60% humidity. Fertilize monthly spring through fall with balanced liquid fertilizer (20-20-20) diluted to half strength. Wipe leaves monthly with damp cloth to remove dust and improve photosynthesis. Repot every 2-3 years in spring when roots fill container. Prune yellowing leaves at base. Watch for spider mites in dry conditions. Toxic to pets.', 'origin': 'Tropical Asia', 'springInterval': 7, 'summerInterval': 7, 'fallInterval': 10, 'winterInterval': 14, 'lightPreference': 'lowIndirect', 'humidityPreference': 'medium', 'temperaturePreference': [18, 27], 'plantToxicity': 'toxic', 'soilPhPreference': 'neutral', 'drainagePreference': 'wellDraining', 'wateringMethod': 'topWatering', 'plantLifeSpan': [5, 15], 'category': 'Houseplants - Low Maintenance', 'hardinessZones': [13, 13], 'growthRate': 'moderate', 'propagationMethods': ['stemCuttings', 'division'], 'categoryIndex': 0}

## Step 5: Convert the Dataset into a DataFrame

The original dataset is stored in JSON format.

In this section, we convert the plant data into a Pandas DataFrame so that it can be easily analyzed, cleaned, and used for building the recommendation system.

In [32]:
plants_df = pd.DataFrame(plant_data)

plants_df.head()

,_metadata,id,typeName,description,commonExamples,careTips,origin,springInterval,summerInterval,fallInterval,...,plantToxicity,soilPhPreference,drainagePreference,wateringMethod,plantLifeSpan,category,hardinessZones,growthRate,propagationMethods,categoryIndex
0,"{'version': '1.9.0', 'totalPlants': 952, 'sort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,aglaonema,Aglaonema,Also known as: Chinese evergreen. Low-light to...,"Aglaonema commutatum (Chinese evergreen), A. p...",Water when top 1-2 inches of soil feels dry. K...,Tropical Asia,7.0,7.0,10.0,...,toxic,neutral,wellDraining,topWatering,"[5, 15]",Houseplants - Low Maintenance,"[13, 13]",moderate,"[stemCuttings, division]",0.0
2,NaN,aglaonema-pink-star,Aglaonema Pink Star,Aglaonema cultivar with pink-splashed variegat...,Aglaonema 'Pink Star',Water when top 1-2 inches of soil feels dry. K...,Tropical Asia,7.0,7.0,10.0,...,toxic,neutral,wellDraining,topWatering,"[5, 15]",Houseplants - Low Maintenance,"[13, 13]",moderate,"[stemCuttings, division]",0.0
3,NaN,aglaonema-red-valentine,Red Valentine Aglaonema,Striking Aglaonema cultivar with deep pink or ...,Aglaonema 'Red Valentine',Water when top 1-2 inches of soil feels dry. K...,Tropical Asia,7.0,7.0,10.0,...,toxic,neutral,wellDraining,topWatering,"[5, 15]",Houseplants - Low Maintenance,"[13, 13]",moderate,"[stemCuttings, division]",0.0
4,NaN,aglaonema-sparkling-sarah,Aglaonema Sparkling Sarah,Colorful Aglaonema cultivar with striking pink...,Aglaonema 'Sparkling Sarah',Water when top 1-2 inches of soil feels dry. K...,Tropical Asia,7.0,7.0,10.0,...,toxic,neutral,wellDraining,topWatering,"[5, 15]",Houseplants - Low Maintenance,"[13, 13]",moderate,"[stemCuttings, division]",0.0

## Step 6: Check the Dataset Structure

We check the number of rows, columns, and available features in the Plantfolio dataset.

In [40]:
print("Dataset shape:", plants_df.shape)

print("\nColumns:")
print(plants_df.columns.tolist())

Dataset shape: (952, 24)

Columns:
['_metadata', 'id', 'typeName', 'description', 'commonExamples', 'careTips', 'origin', 'springInterval', 'summerInterval', 'fallInterval', 'winterInterval', 'lightPreference', 'humidityPreference', 'temperaturePreference', 'plantToxicity', 'soilPhPreference', 'drainagePreference', 'wateringMethod', 'plantLifeSpan', 'category', 'hardinessZones', 'growthRate', 'propagationMethods', 'categoryIndex']

## Step 7: Remove the Metadata Column

The dataset contains a metadata column that does not contain useful information for individual plant records.

We remove this column before further processing.

In [41]:
plants_df = plants_df.drop(columns=["_metadata"], errors="ignore")

print("Metadata column removed successfully!")

Metadata column removed successfully!

## Step 8: Remove Invalid Records

Some dataset entries may not represent actual plants.

We remove records that do not contain a valid plant ID.

In [42]:
plants_df = plants_df.dropna(subset=["id"])

plants_df = plants_df.reset_index(drop=True)

print("Invalid records removed successfully!")
print("Dataset shape:", plants_df.shape)

Invalid records removed successfully!
Dataset shape: (952, 23)

## Step 9: Check Missing Values

We check for missing information in the cleaned plant dataset.

In [43]:
print(plants_df.isnull().sum())

id                         0
typeName                   0
description                0
commonExamples             0
careTips                   0
origin                     0
springInterval            20
summerInterval            43
fallInterval              38
winterInterval           577
lightPreference            0
humidityPreference         0
temperaturePreference      0
plantToxicity              0
soilPhPreference           0
drainagePreference         0
wateringMethod             0
plantLifeSpan              0
category                   0
hardinessZones             0
growthRate                 0
propagationMethods         0
categoryIndex              0
dtype: int64

## Step 10: Select Required Features

We select only the columns required for the main features of the Intelligent Plant Care Recommendation System.

These features include:

1. Basic Plant Care Recommendation
2. Personalized Plant Care Recommendation
3. Plant Care Question Answering

A separate dataset will later be used for NLP-based plant problem identification.

In [45]:
required_columns = [
    "id",
    "typeName",
    "category",
    "description",
    "commonExamples",
    "careTips",
    "lightPreference",
    "humidityPreference",
    "temperaturePreference",
    "springInterval",
    "summerInterval",
    "fallInterval",
    "winterInterval",
    "soilPhPreference",
    "drainagePreference",
    "plantToxicity",
    "growthRate"
]

master_df = plants_df[required_columns].copy()

print("Master dataset created successfully!")
print("Dataset shape:", master_df.shape)

master_df.head()

Master dataset created successfully!
Dataset shape: (952, 17)

,id,typeName,category,description,commonExamples,careTips,lightPreference,humidityPreference,temperaturePreference,springInterval,summerInterval,fallInterval,winterInterval,soilPhPreference,drainagePreference,plantToxicity,growthRate
0,aglaonema,Aglaonema,Houseplants - Low Maintenance,Also known as: Chinese evergreen. Low-light to...,"Aglaonema commutatum (Chinese evergreen), A. p...",Water when top 1-2 inches of soil feels dry. K...,lowIndirect,medium,"[18, 27]",7.0,7.0,10.0,14.0,neutral,wellDraining,toxic,moderate
1,aglaonema-pink-star,Aglaonema Pink Star,Houseplants - Low Maintenance,Aglaonema cultivar with pink-splashed variegat...,Aglaonema 'Pink Star',Water when top 1-2 inches of soil feels dry. K...,brightIndirect,medium,"[18, 27]",7.0,7.0,10.0,14.0,neutral,wellDraining,toxic,moderate
2,aglaonema-red-valentine,Red Valentine Aglaonema,Houseplants - Low Maintenance,Striking Aglaonema cultivar with deep pink or ...,Aglaonema 'Red Valentine',Water when top 1-2 inches of soil feels dry. K...,brightIndirect,medium,"[18, 27]",7.0,7.0,10.0,14.0,neutral,wellDraining,toxic,moderate
3,aglaonema-sparkling-sarah,Aglaonema Sparkling Sarah,Houseplants - Low Maintenance,Colorful Aglaonema cultivar with striking pink...,Aglaonema 'Sparkling Sarah',Water when top 1-2 inches of soil feels dry. K...,brightIndirect,medium,"[18, 27]",7.0,7.0,10.0,14.0,neutral,wellDraining,toxic,moderate
4,aralia-ming,Ming Aralia,Houseplants - Low Maintenance,"Finely textured tropical shrub with lacy, comp...","Polyscias fruticosa (Ming aralia, Parsley aralia)",Water when top 1-2 inches of soil is dry. Keep...,brightIndirect,medium,"[18, 24]",7.0,7.0,10.0,14.0,neutral,wellDraining,mildlyToxic,moderate

## Step 11: Check Missing Values in the Master Dataset

We check missing values only in the columns selected for our project.

In [46]:
print(master_df.isnull().sum())

id                         0
typeName                   0
category                   0
description                0
commonExamples             0
careTips                   0
lightPreference            0
humidityPreference         0
temperaturePreference      0
springInterval            20
summerInterval            43
fallInterval              38
winterInterval           577
soilPhPreference           0
drainagePreference         0
plantToxicity              0
growthRate                 0
dtype: int64

## Step 12: Handle Missing Text Information

Missing text information is replaced with "Not Available" to preserve valid plant records.

In [47]:
text_columns = [
    "typeName",
    "category",
    "description",
    "commonExamples",
    "careTips",
    "lightPreference",
    "humidityPreference",
    "soilPhPreference",
    "drainagePreference",
    "plantToxicity",
    "growthRate"
]

master_df[text_columns] = master_df[text_columns].fillna("Not Available")

print("Missing text values handled successfully!")

Missing text values handled successfully!

## Step 13: Analyze Seasonal Watering Information

Some plants do not have watering interval information for every season.

We preserve missing values rather than inventing watering intervals.

In [48]:
watering_columns = [
    "springInterval",
    "summerInterval",
    "fallInterval",
    "winterInterval"
]

print(master_df[watering_columns].isnull().sum())

springInterval     20
summerInterval     43
fallInterval       38
winterInterval    577
dtype: int64

## Step 14: Check for Duplicate Plant Records

We check whether duplicate plant IDs exist in the master dataset.

In [50]:
duplicate_count = master_df["id"].duplicated().sum()

print("Number of duplicate plant IDs:", duplicate_count)

Number of duplicate plant IDs: 0

## Step 15: Verify the Final Master Dataset

We verify the size and structure of the cleaned master plant dataset.

In [51]:
print("Number of plants:", master_df.shape[0])
print("Number of columns:", master_df.shape[1])

print("\nFirst five plant names:")
print(master_df["typeName"].head())

Number of plants: 952
Number of columns: 17

First five plant names:
0                    Aglaonema
1          Aglaonema Pink Star
2      Red Valentine Aglaonema
3    Aglaonema Sparkling Sarah
4                  Ming Aralia
Name: typeName, dtype: str

## Step 16: Preview Important Plant Information

We preview important plant care information to verify that the dataset is ready for the recommendation system.

In [52]:
preview_columns = [
    "typeName",
    "category",
    "lightPreference",
    "humidityPreference",
    "temperaturePreference",
    "springInterval",
    "summerInterval",
    "careTips"
]

master_df[preview_columns].head()

,typeName,category,lightPreference,humidityPreference,temperaturePreference,springInterval,summerInterval,careTips
0,Aglaonema,Houseplants - Low Maintenance,lowIndirect,medium,"[18, 27]",7.0,7.0,Water when top 1-2 inches of soil feels dry. K...
1,Aglaonema Pink Star,Houseplants - Low Maintenance,brightIndirect,medium,"[18, 27]",7.0,7.0,Water when top 1-2 inches of soil feels dry. K...
2,Red Valentine Aglaonema,Houseplants - Low Maintenance,brightIndirect,medium,"[18, 27]",7.0,7.0,Water when top 1-2 inches of soil feels dry. K...
3,Aglaonema Sparkling Sarah,Houseplants - Low Maintenance,brightIndirect,medium,"[18, 27]",7.0,7.0,Water when top 1-2 inches of soil feels dry. K...
4,Ming Aralia,Houseplants - Low Maintenance,brightIndirect,medium,"[18, 24]",7.0,7.0,Water when top 1-2 inches of soil is dry. Keep...

## Step 17: Save the Master Plant Dataset

The cleaned dataset is saved as a CSV file.

This dataset will act as the main plant knowledge base for the Intelligent Plant Care Recommendation System.

In [53]:
master_df.to_csv(
    "../data/master_plant_dataset.csv",
    index=False
)

print("Master plant dataset saved successfully!")

Master plant dataset saved successfully!

## Step 18: Prepare the Plant Knowledge Base

The cleaned master dataset will now be used as the main knowledge base for the plant care recommendation system.

In [54]:
print("Total plants:", len(master_df))

print("\nAvailable columns:")
print(master_df.columns.tolist())

Total plants: 952

Available columns:
['id', 'typeName', 'category', 'description', 'commonExamples', 'careTips', 'lightPreference', 'humidityPreference', 'temperaturePreference', 'springInterval', 'summerInterval', 'fallInterval', 'winterInterval', 'soilPhPreference', 'drainagePreference', 'plantToxicity', 'growthRate']

## Step 19: Create a Plant Search Function

We create a function that searches for a plant using its name.

The search is case-insensitive, meaning the user can enter the plant name using uppercase or lowercase letters.

In [55]:
def search_plant(plant_name):
    
    plant_name = plant_name.lower().strip()
    
    result = master_df[
        master_df["typeName"].str.lower() == plant_name
    ]
    
    return result

## Step 20: Test the Plant Search Function

We test whether the search function can successfully find a plant from the dataset.

In [56]:
search_plant("Aglaonema")

,id,typeName,category,description,commonExamples,careTips,lightPreference,humidityPreference,temperaturePreference,springInterval,summerInterval,fallInterval,winterInterval,soilPhPreference,drainagePreference,plantToxicity,growthRate
0,aglaonema,Aglaonema,Houseplants - Low Maintenance,Also known as: Chinese evergreen. Low-light to...,"Aglaonema commutatum (Chinese evergreen), A. p...",Water when top 1-2 inches of soil feels dry. K...,lowIndirect,medium,"[18, 27]",7.0,7.0,10.0,14.0,neutral,wellDraining,toxic,moderate

## Step 21: Build the Basic Plant Care Recommendation System

This function takes a plant name as input and provides important information about its care requirements.

In [57]:
def get_plant_care(plant_name):
    
    plant_name = plant_name.lower().strip()
    
    result = master_df[
        master_df["typeName"].str.lower() == plant_name
    ]
    
    if result.empty:
        print("Plant not found in the database.")
        return
    
    plant = result.iloc[0]
    
    print("🌱 PLANT CARE RECOMMENDATION")
    print("=" * 40)
    
    print("\nPlant Name:", plant["typeName"])
    print("Category:", plant["category"])
    
    print("\n📝 Description:")
    print(plant["description"])
    
    print("\n☀️ Light Requirement:")
    print(plant["lightPreference"])
    
    print("\n💧 Humidity Requirement:")
    print(plant["humidityPreference"])
    
    print("\n🌡️ Temperature Range:")
    print(plant["temperaturePreference"])
    
    print("\n🌱 Soil pH Preference:")
    print(plant["soilPhPreference"])
    
    print("\n💧 Drainage Preference:")
    print(plant["drainagePreference"])
    
    print("\n☠️ Plant Toxicity:")
    print(plant["plantToxicity"])
    
    print("\n📈 Growth Rate:")
    print(plant["growthRate"])
    
    print("\n📝 Care Tips:")
    print(plant["careTips"])

## Step 22: Add Seasonal Watering Recommendations

We add watering interval information for different seasons to the plant care recommendation system.

In [58]:
def get_plant_care(plant_name):
    
    plant_name = plant_name.lower().strip()
    
    result = master_df[
        master_df["typeName"].str.lower() == plant_name
    ]
    
    if result.empty:
        print("Plant not found in the database.")
        return
    
    plant = result.iloc[0]
    
    print("🌱 PLANT CARE RECOMMENDATION")
    print("=" * 45)
    
    print("\n🌿 Plant Name:", plant["typeName"])
    print("📂 Category:", plant["category"])
    
    print("\n📝 Description:")
    print(plant["description"])
    
    print("\n☀️ Light Requirement:")
    print(plant["lightPreference"])
    
    print("\n💧 Humidity Requirement:")
    print(plant["humidityPreference"])
    
    print("\n🌡️ Temperature Range:")
    print(plant["temperaturePreference"])
    
    print("\n💦 WATERING SCHEDULE")
    print("Spring:", plant["springInterval"], "days")
    print("Summer:", plant["summerInterval"], "days")
    print("Fall:", plant["fallInterval"], "days")
    print("Winter:", plant["winterInterval"], "days")
    
    print("\n🌱 Soil pH:")
    print(plant["soilPhPreference"])
    
    print("\n🚰 Drainage:")
    print(plant["drainagePreference"])
    
    print("\n☠️ Toxicity:")
    print(plant["plantToxicity"])
    
    print("\n📈 Growth Rate:")
    print(plant["growthRate"])
    
    print("\n📋 CARE TIPS:")
    print(plant["careTips"])

## Step 24: Create a Flexible Plant Search

We improve the search system so that it can find plants even when the user enters only part of the plant name.

In [60]:
def flexible_search(plant_name):
    
    plant_name = plant_name.lower().strip()
    
    result = master_df[
        master_df["typeName"]
        .str.lower()
        .str.contains(plant_name, na=False)
    ]
    
    return result[["typeName", "category"]]

## Step 25: Test the Flexible Plant Search

We test whether the flexible search function can find plants when the user enters only part of a plant name.

In [76]:
flexible_search("holy")

       typeName category
760  Holy Basil    Herbs

## Step 26: Define Common Plant Names

Users may search for plants using common everyday names.

We create a list of common plants to check whether they are available in the Plantfolio dataset and identify the corresponding names used in the dataset.

In [77]:
common_plants = [

    # Indian and medicinal plants
    "tulsi",
    "neem",
    "aloe vera",
    "ashwagandha",
    "mint",
    "lemongrass",
    "curry leaf",

    # Common flowers
    "rose",
    "hibiscus",
    "jasmine",
    "marigold",
    "sunflower",
    "bougainvillea",
    "lotus",

    # Common indoor plants
    "money plant",
    "snake plant",
    "spider plant",
    "peace lily",
    "rubber plant",
    "jade plant",
    "lucky bamboo",
    "areca palm",

    # Herbs
    "basil",
    "coriander",
    "parsley",
    "rosemary",
    "thyme",
    "oregano",

    # Fruits and trees
    "mango",
    "banana",
    "lemon",
    "guava",
    "papaya",
    "pomegranate",

    # Vegetables
    "tomato",
    "chili",
    "potato",
    "spinach",

    # Popular houseplants
    "pothos",
    "monstera",
    "philodendron",
    "fern",
    "orchid",
    "cactus",
    "succulent"
]

print("Total common plant names:", len(common_plants))

Total common plant names: 45

## Step 27: Search Common Plant Names in the Plantfolio Dataset

We search the Plantfolio dataset for possible matches for each common plant name.

This helps us identify the exact plant names used in the dataset.

In [79]:
for plant_name in common_plants:

    matches = flexible_search(plant_name)

    print("\n" + "=" * 60)
    print("COMMON NAME:", plant_name.upper())

    if matches.empty:
        print("No direct match found")

    else:
        print("POSSIBLE PLANTFOLIO MATCHES:")

        for match in matches["typeName"].tolist():
            print("-", match)

============================================================
COMMON NAME: TULSI
No direct match found

============================================================
COMMON NAME: NEEM
POSSIBLE PLANTFOLIO MATCHES:
- Neem Tree

============================================================
COMMON NAME: ALOE VERA
POSSIBLE PLANTFOLIO MATCHES:
- Aloe Vera

============================================================
COMMON NAME: ASHWAGANDHA
POSSIBLE PLANTFOLIO MATCHES:
- Ashwagandha

============================================================
COMMON NAME: MINT
POSSIBLE PLANTFOLIO MATCHES:
- Catmint
- Mint
- Peppermint

============================================================
COMMON NAME: LEMONGRASS
POSSIBLE PLANTFOLIO MATCHES:
- Lemongrass

============================================================
COMMON NAME: CURRY LEAF
No direct match found

============================================================
COMMON NAME: ROSE
POSSIBLE PLANTFOLIO MATCHES:
- Cape Primrose
- Calathea Roseopicta
- Knock Out Rose
- Rose of Sharon
- Rosemary
- Roses
- Primrose
- Moss Rose
- Climbing Rose
- Tuberose
- Alpine Primrose

============================================================
COMMON NAME: HIBISCUS
POSSIBLE PLANTFOLIO MATCHES:
- Tropical Hibiscus
- Hardy Hibiscus

============================================================
COMMON NAME: JASMINE
POSSIBLE PLANTFOLIO MATCHES:
- Jasmine
- Star Jasmine

============================================================
COMMON NAME: MARIGOLD
POSSIBLE PLANTFOLIO MATCHES:
- African Marigold
- Marigolds

============================================================
COMMON NAME: SUNFLOWER
POSSIBLE PLANTFOLIO MATCHES:
- Maximilian Sunflower
- Sunflower
- Oil Sunflower
- Sunflower Sprouts

============================================================
COMMON NAME: BOUGAINVILLEA
POSSIBLE PLANTFOLIO MATCHES:
- Bougainvillea

============================================================
COMMON NAME: LOTUS
POSSIBLE PLANTFOLIO MATCHES:
- Lotus

============================================================
COMMON NAME: MONEY PLANT
POSSIBLE PLANTFOLIO MATCHES:
- Chinese Money Plant

============================================================
COMMON NAME: SNAKE PLANT
POSSIBLE PLANTFOLIO MATCHES:
- Cylindrical Snake Plant
- Bird's Nest Snake Plant
- Moonshine Snake Plant
- Snake Plants

============================================================
COMMON NAME: SPIDER PLANT
POSSIBLE PLANTFOLIO MATCHES:
- Spider Plants

============================================================
COMMON NAME: PEACE LILY
POSSIBLE PLANTFOLIO MATCHES:
- Peace Lily Sensation
- Domino Peace Lily

============================================================
COMMON NAME: RUBBER PLANT
POSSIBLE PLANTFOLIO MATCHES:
- Rubber Plant
- Burgundy Rubber Plant
- Ruby Rubber Plant
- Baby Rubber Plant

============================================================
COMMON NAME: JADE PLANT
POSSIBLE PLANTFOLIO MATCHES:
- Jade Plant

============================================================
COMMON NAME: LUCKY BAMBOO
POSSIBLE PLANTFOLIO MATCHES:
- Lucky Bamboo

============================================================
COMMON NAME: ARECA PALM
POSSIBLE PLANTFOLIO MATCHES:
- Areca Palm

============================================================
COMMON NAME: BASIL
POSSIBLE PLANTFOLIO MATCHES:
- Basil
- Holy Basil
- Basil Microgreens

============================================================
COMMON NAME: CORIANDER
POSSIBLE PLANTFOLIO MATCHES:
- Vietnamese Coriander

============================================================
COMMON NAME: PARSLEY
POSSIBLE PLANTFOLIO MATCHES:
- Parsley

============================================================
COMMON NAME: ROSEMARY
POSSIBLE PLANTFOLIO MATCHES:
- Rosemary

============================================================
COMMON NAME: THYME
POSSIBLE PLANTFOLIO MATCHES:
- Creeping Thyme
- Thyme

============================================================
COMMON NAME: OREGANO
POSSIBLE PLANTFOLIO MATCHES:
- Oregano

============================================================
COMMON NAME: MANGO
POSSIBLE PLANTFOLIO MATCHES:
- Mango

============================================================
COMMON NAME: BANANA
POSSIBLE PLANTFOLIO MATCHES:
- String of Bananas
- Banana

============================================================
COMMON NAME: LEMON
POSSIBLE PLANTFOLIO MATCHES:
- Lemon Button Fern
- Lemon Cypress
- Lemon Cucumber
- Lemon Tree
- Lemon Balm
- Lemongrass

============================================================
COMMON NAME: GUAVA
POSSIBLE PLANTFOLIO MATCHES:
- Guava

============================================================
COMMON NAME: PAPAYA
POSSIBLE PLANTFOLIO MATCHES:
- Papaya

============================================================
COMMON NAME: POMEGRANATE
POSSIBLE PLANTFOLIO MATCHES:
- Pomegranate

============================================================
COMMON NAME: TOMATO
POSSIBLE PLANTFOLIO MATCHES:
- Cherry Tomato
- Roma Tomato
- Tomatoes

============================================================
COMMON NAME: CHILI
No direct match found

============================================================
COMMON NAME: POTATO
POSSIBLE PLANTFOLIO MATCHES:
- Sweet Potato Vine
- Potatoes
- Sweet Potatoes
- Sweet Potato

============================================================
COMMON NAME: SPINACH
POSSIBLE PLANTFOLIO MATCHES:
- Malabar Spinach
- Spinach
- Water Spinach

============================================================
COMMON NAME: POTHOS
POSSIBLE PLANTFOLIO MATCHES:
- Pothos
- Cebu Blue Pothos
- Jade Pothos
- Shangri La Pothos
- Golden Pothos
- Marble Queen Pothos
- Neon Pothos
- Silver Satin Pothos

============================================================
COMMON NAME: MONSTERA
POSSIBLE PLANTFOLIO MATCHES:
- Monstera Adansonii
- Monstera Albo
- Monstera Aurea
- Monstera Esqueleto
- Monstera Lechleriana
- Monstera Peru
- Monstera Siltepecana
- Monstera Standleyana
- Thai Constellation Monstera
- Mini Monstera

============================================================
COMMON NAME: PHILODENDRON
POSSIBLE PLANTFOLIO MATCHES:
- Philodendron Congo
- Philodendron Burle Marx
- Philodendron Birkin
- Silver Leaf Philodendron
- Philodendron Florida Ghost
- Philodendron Gloriosum
- Philodendron Heartleaf
- Philodendron Jose Buono
- Philodendron Mamei
- Philodendron Melanochrysum
- Philodendron Micans
- Philodendron Pink Princess
- Philodendron Plowmanii
- Philodendron Red Moon
- Ring of Fire Philodendron
- Tree Philodendron
- Silver Philodendron
- Philodendron Verrucosum
- White Variegated Philodendron
- White Princess Philodendron
- Philodendron Xanadu
- Philodendron Brasil

============================================================
COMMON NAME: FERN
POSSIBLE PLANTFOLIO MATCHES:
- Asparagus Fern
- Bird's Nest Fern
- Dwarf Tree Fern
- Boston Ferns
- Button Fern
- Deer Fern
- Ferns
- Japanese Painted Fern
- Maidenhair Ferns
- Kangaroo Paw Fern
- Crocodile Fern
- Lemon Button Fern
- Blue Star Fern
- Brake Fern
- Rabbit's Foot Fern
- Staghorn Fern
- Java Fern
- Resurrection Fern

============================================================
COMMON NAME: ORCHID
POSSIBLE PLANTFOLIO MATCHES:
- Orchid Cactus
- Phalaenopsis Orchids
- Dendrobium Orchid
- Oncidium Orchid
- Orchids
- Slipper Orchid
- Vanda Orchid

============================================================
COMMON NAME: CACTUS
POSSIBLE PLANTFOLIO MATCHES:
- Pencil Cactus
- Barrel Cactus
- Christmas Cactus
- Easter Cactus
- Easter Lily Cactus
- Orchid Cactus
- Chin Cactus
- Pincushion Cactus
- Old Lady Cactus
- Bunny Ears Cactus
- Ball Cactus
- Rat Tail Cactus
- Saguaro Cactus
- Star Cactus
- Thanksgiving Cactus

============================================================
COMMON NAME: SUCCULENT
POSSIBLE PLANTFOLIO MATCHES:
- Succulents

## Step 28: Create the Common Plant Name Alignment Table

The Plantfolio dataset may use names that are different from the common names entered by users.

We create an alignment table that connects common user plant names with verified plant names available in the Plantfolio dataset.

Only clear and verified mappings are included at this stage.

In [80]:
common_name_alignment = {
    
    # Indian and medicinal plants
    "tulsi": "Holy Basil",
    "neem": "Neem Tree",
    "aloe vera": "Aloe Vera",
    "ashwagandha": "Ashwagandha",
    "mint": "Mint",
    "lemongrass": "Lemongrass",
    
    # Flowers
    "rose": "Roses",
    "hibiscus": "Tropical Hibiscus",
    "jasmine": "Jasmine",
    "marigold": "Marigolds",
    "sunflower": "Sunflower",
    "bougainvillea": "Bougainvillea",
    "lotus": "Lotus",
    
    # Indoor plants
    "snake plant": "Snake Plants",
    "spider plant": "Spider Plants",
    "rubber plant": "Rubber Plant",
    "jade plant": "Jade Plant",
    "lucky bamboo": "Lucky Bamboo",
    "areca palm": "Areca Palm",
    
    # Herbs
    "parsley": "Parsley",
    "rosemary": "Rosemary",
    "thyme": "Thyme",
    "oregano": "Oregano",
    
    # Fruits and trees
    "mango": "Mango",
    "banana": "Banana",
    "guava": "Guava",
    "papaya": "Papaya",
    "pomegranate": "Pomegranate",
    
    # Vegetables
    "spinach": "Spinach",
    
    # Houseplants
    "pothos": "Pothos",
    
    # General categories
    "succulent": "Succulents"
}

print("Total verified plant mappings:", len(common_name_alignment))

Total verified plant mappings: 31

## Step 29: Verify the Common Plant Name Alignment Table

We verify that every Plantfolio plant name used in the alignment table actually exists in the master dataset.

In [82]:
for common_name, dataset_name in common_name_alignment.items():
    
    exists = master_df[
        master_df["typeName"]
        .str.lower() == dataset_name.lower()
    ]
    
    if exists.empty:
        print(f"❌ {common_name} → {dataset_name}: NOT FOUND")
    
    else:
        print(f"✅ {common_name} → {dataset_name}: FOUND")

✅ tulsi → Holy Basil: FOUND
✅ neem → Neem Tree: FOUND
✅ aloe vera → Aloe Vera: FOUND
✅ ashwagandha → Ashwagandha: FOUND
✅ mint → Mint: FOUND
✅ lemongrass → Lemongrass: FOUND
✅ rose → Roses: FOUND
✅ hibiscus → Tropical Hibiscus: FOUND
✅ jasmine → Jasmine: FOUND
✅ marigold → Marigolds: FOUND
✅ sunflower → Sunflower: FOUND
✅ bougainvillea → Bougainvillea: FOUND
✅ lotus → Lotus: FOUND
✅ snake plant → Snake Plants: FOUND
✅ spider plant → Spider Plants: FOUND
✅ rubber plant → Rubber Plant: FOUND
✅ jade plant → Jade Plant: FOUND
✅ lucky bamboo → Lucky Bamboo: FOUND
✅ areca palm → Areca Palm: FOUND
✅ parsley → Parsley: FOUND
✅ rosemary → Rosemary: FOUND
✅ thyme → Thyme: FOUND
✅ oregano → Oregano: FOUND
✅ mango → Mango: FOUND
✅ banana → Banana: FOUND
✅ guava → Guava: FOUND
✅ papaya → Papaya: FOUND
✅ pomegranate → Pomegranate: FOUND
✅ spinach → Spinach: FOUND
✅ pothos → Pothos: FOUND
✅ succulent → Succulents: FOUND

## Step 30: Add Additional Verified Common Plant Mappings

We add additional common plant names that have clear corresponding entries in the Plantfolio dataset.

In [83]:
additional_mappings = {
    
    "money plant": "Pothos",
    "lemon": "Lemon Tree",
    "tomato": "Tomatoes",
    "potato": "Potatoes",
    "coriander": "Vietnamese Coriander"
}

common_name_alignment.update(additional_mappings)

print("Additional mappings added successfully!")
print("Total mappings:", len(common_name_alignment))

Additional mappings added successfully!
Total mappings: 36

## Step 31: Create the Plant Alias Dictionary

The verified common plant name alignment table is converted into an alias dictionary.

The dictionary will be used by the smart plant search system to understand common plant names entered by users.

In [84]:
plant_aliases = common_name_alignment.copy()

print("Plant alias dictionary created successfully!")
print("Total aliases:", len(plant_aliases))

Plant alias dictionary created successfully!
Total aliases: 36

## Step 32: Standardize User Plant Names

Users may enter common plant names that differ from the names stored in the Plantfolio dataset.

This function checks the plant alias dictionary and converts common names into the corresponding Plantfolio names.

In [85]:
def standardize_plant_name(plant_name):
    
    # Convert user input to lowercase and remove extra spaces
    plant_name = plant_name.lower().strip()
    
    # Check if the name exists in the alias dictionary
    if plant_name in plant_aliases:
        return plant_aliases[plant_name]
    
    # If no alias is found, return the original name
    return plant_name

## Step 33: Test the Plant Name Standardization Function

We test whether common plant names are correctly converted into the names used in the Plantfolio dataset.

In [86]:
test_names = [
    "tulsi",
    "neem",
    "money plant",
    "rose",
    "aglaonema"
]

for name in test_names:
    
    standardized_name = standardize_plant_name(name)
    
    print(f"{name} → {standardized_name}")

tulsi → Holy Basil
neem → Neem Tree
money plant → Pothos
rose → Roses
aglaonema → aglaonema

## Step 34: Create the Smart Plant Search System

The smart plant search system understands common plant names using the alias dictionary.

It first converts the user's input into a standardized plant name, then searches the Plantfolio dataset for an exact match.

If an exact match is not found, it performs a flexible search.

In [87]:
def smart_search_plant(plant_name):
    
    # Standardize the plant name using aliases
    standardized_name = standardize_plant_name(plant_name)
    
    # Convert to lowercase
    search_name = standardized_name.lower()
    
    # Try to find an exact match
    exact_result = master_df[
        master_df["typeName"]
        .str.lower() == search_name
    ]
    
    # Return exact match if found
    if not exact_result.empty:
        return exact_result
    
    # If no exact match is found, use flexible search
    partial_result = master_df[
        master_df["typeName"]
        .str.lower()
        .str.contains(search_name, na=False)
    ]
    
    return partial_result

## Step 35: Test the Smart Plant Search System

We test the smart search system using common names and direct Plantfolio plant names.

In [88]:
test_plants = [
    "tulsi",
    "neem",
    "money plant",
    "aloe vera",
    "aglaonema",
    "snake plant"
]

for plant_name in test_plants:
    
    result = smart_search_plant(plant_name)
    
    print("\n" + "=" * 50)
    print("USER INPUT:", plant_name)
    
    if result.empty:
        print("Plant not found")
    
    else:
        print("MATCH FOUND:")
        
        for name in result["typeName"].tolist():
            print("-", name)

==================================================
USER INPUT: tulsi
MATCH FOUND:
- Holy Basil

==================================================
USER INPUT: neem
MATCH FOUND:
- Neem Tree

==================================================
USER INPUT: money plant
MATCH FOUND:
- Pothos

==================================================
USER INPUT: aloe vera
MATCH FOUND:
- Aloe Vera

==================================================
USER INPUT: aglaonema
MATCH FOUND:
- Aglaonema

==================================================
USER INPUT: snake plant
MATCH FOUND:
- Snake Plants

## Step 36: Build the Smart Plant Care Recommendation System

This function uses the smart plant search system to find a plant and display its important care requirements.

In [89]:
def get_smart_plant_care(plant_name):
    
    # Search for the plant
    result = smart_search_plant(plant_name)
    
    # Check if the plant was found
    if result.empty:
        print("❌ Plant not found in the database.")
        return
    
    # Select the first matching plant
    plant = result.iloc[0]
    
    print("=" * 50)
    print("🌱 PLANT CARE RECOMMENDATION")
    print("=" * 50)
    
    print("\n🌿 Plant Name:", plant["typeName"])
    print("📂 Category:", plant["category"])
    
    print("\n📝 Description:")
    print(plant["description"])
    
    print("\n☀️ Light Requirement:")
    print(plant["lightPreference"])
    
    print("\n💧 Humidity Requirement:")
    print(plant["humidityPreference"])
    
    print("\n🌡️ Temperature Range:")
    print(plant["temperaturePreference"])
    
    print("\n💦 WATERING SCHEDULE:")
    print("Spring:", plant["springInterval"], "days")
    print("Summer:", plant["summerInterval"], "days")
    print("Fall:", plant["fallInterval"], "days")
    print("Winter:", plant["winterInterval"], "days")
    
    print("\n🌱 Soil Preference:")
    print(plant["soilPhPreference"])
    
    print("\n🚰 Drainage:")
    print(plant["drainagePreference"])
    
    print("\n☠️ Toxicity:")
    print(plant["plantToxicity"])
    
    print("\n📈 Growth Rate:")
    print(plant["growthRate"])
    
    print("\n📋 CARE TIPS:")
    print(plant["careTips"])

## Step 37: Test the Complete Smart Plant Care Recommendation System

We test the complete system using common plant names entered by users.

In [92]:
get_smart_plant_care("snake plant")

==================================================
🌱 PLANT CARE RECOMMENDATION
==================================================

🌿 Plant Name: Snake Plants
📂 Category: Houseplants - Low Maintenance

📝 Description:
Also known as: Mother-in-law's tongue. Extremely low-maintenance succulents in the Asparagaceae family with upright sword-like leaves. Includes various cultivars with different leaf shapes and patterns.

☀️ Light Requirement:
brightIndirect

💧 Humidity Requirement:
low

🌡️ Temperature Range:
[18, 27]

💦 WATERING SCHEDULE:
Spring: 14.0 days
Summer: 14.0 days
Fall: 21.0 days
Winter: 30.0 days

🌱 Soil Preference:
neutral

🚰 Drainage:
excellentDrainage

☠️ Toxicity:
toxic

📈 Growth Rate:
slow

📋 CARE TIPS:
Water only when soil is completely dry (every 2-8 weeks depending on conditions). Very drought tolerant due to water storage in leaves. Bright indirect to direct light preferred; tolerates low light but grows slowly. Low humidity is fine. Fertilize 2-3 times per year during growing season with succulent fertilizer at quarter strength. Repot only when pot breaks or plant becomes top-heavy (every 5-10 years). Remove dead leaves at base by pulling gently. Divide offsets when repotting. Overwatering is the main cause of death - when in doubt, wait longer. Toxic to pets. Remove yellowing or damaged leaves promptly.

## Step 38: Define Plant Problem Categories

Before training the NLP model, we define the common plant problem categories that the system should identify.

These categories will be used as labels for the NLP classification model.

In [93]:
problem_categories = [
    "overwatering",
    "underwatering",
    "low_light",
    "nutrient_deficiency",
    "pest_problem",
    "fungal_disease",
    "temperature_stress",
    "healthy"
]

print("Plant problem categories:")
for category in problem_categories:
    print("-", category)

Plant problem categories:
- overwatering
- underwatering
- low_light
- nutrient_deficiency
- pest_problem
- fungal_disease
- temperature_stress
- healthy

## Step 38: Define Plant Problem Categories

Before training the NLP model, we define the common plant problem categories that the system should identify.

These categories will be used as labels for the NLP classification model.

In [94]:
problem_categories = [
    "overwatering",
    "underwatering",
    "low_light",
    "nutrient_deficiency",
    "pest_problem",
    "fungal_disease",
    "temperature_stress",
    "healthy"
]

print("Plant problem categories:")
for category in problem_categories:
    print("-", category)

Plant problem categories:
- overwatering
- underwatering
- low_light
- nutrient_deficiency
- pest_problem
- fungal_disease
- temperature_stress
- healthy

## Step 39: Create the Plant Problem Dataset

We create a dataset containing plant problem descriptions and their corresponding problem categories.

This dataset will be used to train the NLP classification model.

In [1]:
import pandas as pd

# ============================================================
# COMPLETE PLANT PROBLEM DATASET
# ============================================================

problem_data = {


    # ========================================================
    # OVERWATERING
    # ========================================================

    "overwatering": [

        "The leaves are turning yellow and the soil is very wet",
        "My plant looks weak and the soil stays wet for many days",
        "Leaves are falling and the soil is soggy",
        "I water my plant every day and now the leaves are yellow",
        "The plant is drooping even though I water it regularly",
        "The potting soil remains wet for a long time",
        "My plant looks unhealthy because I give it too much water",
        "The soil is always soggy",
        "Yellow leaves are falling from my plant",
        "I think I have watered my plant too much",
        "My plant is drooping but the soil is already wet",
        "The leaves are soft and yellow",
        "Water stays in the pot for too long",
        "I keep watering but the plant looks worse",
        "The soil never seems to dry",
        "My plant has yellow leaves and wet soil",
        "I may be watering the plant too frequently",
        "The plant looks weak and the soil is constantly moist",
        "Leaves are becoming yellow after frequent watering",
        "My plant is wilting even though the soil is wet",
        "The pot feels heavy because the soil is full of water",
        "I accidentally watered the plant several times this week",
        "The lower leaves are yellow and dropping",
        "My plant looks unhealthy after excessive watering",
        "The soil feels wet every time I check it",
        "Why are my leaves yellow when I water regularly",
        "Plant soil is soggy all the time",
        "I think the plant is getting too much water",
        "The leaves are drooping and the soil is soaking wet",
        "My plant has been sitting in wet soil for days",
        "I water the plant too often",
        "The soil has not dried since the last watering",
        "My plant looks limp even though it has plenty of water",
        "There is always moisture in the pot",
        "The plant became yellow after I increased watering"
    ],


    # ========================================================
    # UNDERWATERING
    # ========================================================

    "underwatering": [

        "The soil is very dry and the leaves are drooping",
        "My plant looks dry and weak",
        "The leaves are crispy and dry",
        "I forgot to water my plant for many days",
        "The soil is completely dry",
        "The plant is wilting because it has not received water",
        "The leaves are dry and falling off",
        "My plant looks thirsty",
        "The soil dries out very quickly",
        "The leaves are turning brown and crispy",
        "I have not watered my plant for a week",
        "My plant is drooping and the soil is dry",
        "The leaves feel dry and brittle",
        "The plant looks weak because I forgot to water it",
        "The soil has become extremely dry",
        "My plant is wilting from lack of water",
        "The leaves are curling and dry",
        "I think my plant needs more water",
        "The plant looks dehydrated",
        "The leaves are becoming dry at the edges",
        "The potting soil is dry all the way through",
        "I rarely water this plant",
        "The plant becomes droopy when I forget watering",
        "The leaves look shriveled and dry",
        "My plant has not been watered recently",
        "The soil is dusty and dry",
        "The leaves are hanging down because the plant is dry",
        "My plant looks better after I water it",
        "I forgot to water it for several days",
        "The plant is drying out",
        "Leaves are crispy because the soil is dry",
        "My plant is wilting and the pot is very dry",
        "The soil has no moisture",
        "I think the plant is not getting enough water",
        "The leaves are dry and the plant looks thirsty"
    ],


    # ========================================================
    # LOW LIGHT
    # ========================================================

    "low_light": [

        "My plant is growing slowly in a dark room",
        "The plant does not receive much sunlight",
        "The leaves are becoming pale because the room is dark",
        "My plant is not growing well indoors",
        "The plant is kept far from the window",
        "There is very little natural light in my room",
        "The plant looks weak because it does not get enough light",
        "My plant is stretching toward the window",
        "The stems are becoming long and weak",
        "The plant is growing slowly because the area is too dark",
        "My room does not get much sunlight",
        "The plant is kept in a shaded corner",
        "The leaves look pale and the plant is growing slowly",
        "My plant does not receive enough sunlight",
        "The plant is leaning toward the light source",
        "The stems are thin and stretched",
        "The plant has become leggy indoors",
        "Growth is very slow in this dark location",
        "My plant is far away from any window",
        "The leaves are losing their healthy color",
        "The plant is not getting sufficient light",
        "The room remains dark during most of the day",
        "My plant is growing toward the window",
        "The plant looks stretched because of low light",
        "There is no direct or bright light where I keep it",
        "The plant growth has slowed in a dark area",
        "My plant is kept in a place with very little light",
        "The leaves are pale and growth is weak",
        "The plant is not receiving enough daylight",
        "My indoor plant is struggling because the room is too dark",
        "The stems are long because it is searching for light",
        "The plant has weak growth in low light",
        "My plant needs a brighter location",
        "There is not enough sunlight in this room",
        "The plant looks weak in the dark corner"
    ],


    # ========================================================
    # NUTRIENT DEFICIENCY
    # ========================================================

    "nutrient_deficiency": [

        "The leaves are yellow even though I water properly",
        "My plant is growing very slowly despite good care",
        "The leaves look pale and weak",
        "The plant may not be getting enough nutrients",
        "Older leaves are turning yellow",
        "New growth is small and weak",
        "The leaves have yellow areas between the veins",
        "My plant has poor growth despite proper watering",
        "The soil may not have enough nutrients",
        "The plant looks pale and unhealthy",
        "The leaves are losing their green color",
        "Growth has slowed even though light and water seem fine",
        "The plant has small new leaves",
        "The leaves are pale green",
        "My plant may need fertilizer",
        "The plant looks weak even with proper watering",
        "Yellowing is happening without overwatering",
        "The leaves have unusual discoloration",
        "My plant has stopped growing well",
        "The plant seems to lack nutrients",
        "The leaves are yellow but the soil conditions are normal",
        "Growth is poor and leaves look pale",
        "My plant has weak new growth",
        "The leaves are not a healthy green color",
        "The plant has been in the same soil for a long time",
        "I have not fertilized the plant for months",
        "The leaves look pale despite receiving enough light",
        "The plant is growing slowly and looks nutrient deficient",
        "New leaves are smaller than usual",
        "The plant looks unhealthy without any obvious pest problem",
        "There are yellow patches on otherwise healthy leaves",
        "My plant might need more nutrients",
        "The growth is weak and leaves are pale",
        "The soil may be exhausted",
        "The plant has poor growth and yellow leaves"
    ],


    # ========================================================
    # PEST PROBLEM
    # ========================================================

    "pest_problem": [

        "There are tiny insects on my plant",
        "I can see bugs underneath the leaves",
        "The leaves have small holes",
        "There are tiny insects moving on the stems",
        "Something is eating my plant leaves",
        "I found small bugs on the plant",
        "The leaves are damaged by insects",
        "There are insects hiding under the leaves",
        "My plant has sticky leaves and tiny bugs",
        "I can see web like material on the plant",
        "The leaves have been chewed",
        "There are white insects on my plant",
        "Small black bugs are on the leaves",
        "The plant has tiny pests",
        "I see insects crawling around the stems",
        "There are small insects in groups on the leaves",
        "The leaves have bite marks",
        "My plant has a pest infestation",
        "There are tiny creatures on the underside of the leaves",
        "The plant leaves are damaged and I can see insects",
        "I found bugs near the new growth",
        "The leaves have unusual holes",
        "Something is damaging the leaves",
        "There are tiny white bugs on the plant",
        "The plant has sticky residue and insects",
        "I can see small pests moving",
        "The leaves are being eaten",
        "There are bugs around the stems",
        "My plant seems to have insects",
        "Tiny insects are covering parts of the plant",
        "I noticed pests on the leaves",
        "The plant has webbing and tiny insects",
        "There are small bugs hiding in the leaf joints",
        "The leaves are damaged by pests",
        "I think insects are attacking my plant"
    ],


    # ========================================================
    # FUNGAL DISEASE
    # ========================================================

    "fungal_disease": [

        "Brown spots are spreading across the leaves",
        "There are dark spots on the leaves",
        "The plant has unusual patches that are spreading",
        "The leaves have black spots",
        "White powder is appearing on the leaves",
        "There are fungal looking spots on my plant",
        "The spots on the leaves are getting bigger",
        "The plant has circular brown patches",
        "There is powdery growth on the leaves",
        "Dark patches are spreading across the foliage",
        "The leaves have unusual fungal marks",
        "Brown spots keep appearing on new leaves",
        "There is white powder on the plant",
        "The leaf spots are spreading quickly",
        "The plant has black and brown patches",
        "There is mold like growth on the leaves",
        "The leaves have strange dark marks",
        "The spots look like a disease",
        "My plant has patches that continue spreading",
        "The leaves have powdery white material",
        "There are brown lesions on the foliage",
        "Dark spots appeared after humid weather",
        "The plant leaves have a disease like pattern",
        "Spots are spreading from one leaf to another",
        "There is fuzzy growth on the leaves",
        "The leaves have dark circular spots",
        "I think my plant has a fungal infection",
        "Brown patches are increasing on the plant",
        "The leaves have unusual spots and discoloration",
        "White powder keeps appearing on the leaves",
        "There are spreading brown marks on the foliage",
        "The plant has black spots that are getting worse",
        "The leaves have a possible fungal disease",
        "The patches on the plant are spreading",
        "My plant has dark spots and powdery growth"
    ],


    # ========================================================
    # TEMPERATURE STRESS
    # ========================================================

    "temperature_stress": [

        "My plant became weak after being exposed to cold weather",
        "The leaves were damaged after a sudden temperature change",
        "The plant is suffering because the room is too hot",
        "Cold air from the window is affecting my plant",
        "The plant was exposed to extreme heat",
        "The leaves became damaged after a cold night",
        "My plant is close to a heater",
        "The plant is near an air conditioner",
        "The temperature around the plant changes frequently",
        "My plant looks stressed during very hot weather",
        "The leaves were damaged after frost",
        "The plant is exposed to cold drafts",
        "Extreme heat is making the leaves wilt",
        "The plant became weak after being moved outside in cold weather",
        "The room temperature is too low for my plant",
        "My plant is suffering during a heatwave",
        "The leaves look damaged after extreme temperatures",
        "The plant is close to a source of hot air",
        "Cold weather caused the leaves to droop",
        "The plant is affected by very high temperatures",
        "My plant does not tolerate the cold",
        "The temperature dropped suddenly and the plant looks weak",
        "The plant is stressed because of heat",
        "My plant is near a cold window",
        "The leaves started wilting during extreme heat",
        "The plant was exposed to freezing conditions",
        "The temperature in the room changes too much",
        "Hot weather is stressing my plant",
        "The plant looks damaged after a sudden cold spell",
        "My plant is affected by a very hot environment",
        "The plant is exposed to cold air regularly",
        "Extreme temperatures are affecting the plant",
        "The leaves became weak after temperature changes",
        "My plant may be stressed by heat or cold",
        "The plant is not in a suitable temperature range"
    ],


    # ========================================================
    # HEALTHY
    # ========================================================

    "healthy": [

        "My plant looks healthy and is growing well",
        "The leaves are green and healthy",
        "My plant is doing very well",
        "There are no visible problems with my plant",
        "The plant is growing normally",
        "My plant looks fresh and healthy",
        "The leaves look green and strong",
        "Everything seems fine with my plant",
        "The plant is growing new leaves normally",
        "My plant looks completely healthy",
        "There are no spots or insects on the leaves",
        "The plant has healthy green foliage",
        "My plant is growing well with no problems",
        "The leaves look normal",
        "The plant is doing great",
        "My plant looks strong and healthy",
        "New growth is appearing normally",
        "The plant has no visible damage",
        "Everything looks normal with my plant",
        "My plant is healthy",
        "The leaves are green and there are no problems",
        "The plant is growing steadily",
        "My plant looks good and healthy",
        "There are no signs of disease",
        "The plant has normal healthy growth",
        "My plant is doing fine",
        "The leaves look fresh and green",
        "The plant seems perfectly healthy",
        "There are no unusual symptoms",
        "My plant has healthy new growth",
        "The plant looks normal",
        "Everything is okay with my plant",
        "My plant is growing properly",
        "The leaves are healthy and green",
        "No major problem is visible"
    ],


    # ========================================================
    # ROOT ROT
    # ========================================================

    "root_rot": [

        "The roots are brown and mushy",
        "My plant is wilting even though the soil is wet and the roots look damaged",
        "There is a bad smell coming from the soil and the roots are soft",
        "The roots look black and unhealthy",
        "My plant has mushy roots",
        "The roots are rotting in the wet soil",
        "I removed the plant and found dark soft roots",
        "The plant is wilting despite having plenty of water and damaged roots",
        "The roots are brown and falling apart",
        "There is a rotten smell coming from the root area",
        "My plant has soft black roots",
        "The roots are unhealthy and mushy",
        "The plant has root damage from staying wet too long",
        "I think the roots are rotting",
        "The roots are dark and soft instead of firm",
        "The plant is weak and the roots look rotten",
        "There is a foul smell from the potting soil",
        "The roots have become brown and slimy",
        "My plant is declining and the roots are damaged",
        "The root system looks unhealthy",
        "The roots are turning black and mushy",
        "The plant is wilting while the roots remain wet and damaged",
        "I can see rotting roots when I remove the plant from the pot",
        "The roots are soft and decomposing",
        "There is a bad odor near the roots",
        "My plant has unhealthy roots that are falling apart",
        "The root area looks rotten",
        "The roots have become dark because of excess moisture",
        "The plant is weak and the root system is damaged",
        "I found mushy brown roots in the pot",
        "The roots smell bad and look unhealthy",
        "My plant may have root rot",
        "The roots are black instead of white and firm",
        "The plant is wilting because its roots are rotting",
        "I found soft rotten roots after checking the plant"
    ],


    # ========================================================
    # SUNBURN
    # ========================================================

    "sunburn": [

        "My plant has brown scorched patches after direct sunlight",
        "The leaves look burned from too much sun",
        "There are bleached spots on the leaves",
        "My plant was damaged after being moved into direct sunlight",
        "The leaves have dry brown patches where sunlight hits them",
        "Too much strong sunlight is burning the leaves",
        "The plant has pale bleached areas from intense sun",
        "The leaves became scorched during hot sunny weather",
        "My plant developed brown patches after too much direct sun",
        "The foliage looks burned on the side facing the sun",
        "Strong sunlight is damaging my plant",
        "The leaves have sunburned spots",
        "The plant was fine indoors but burned after being placed outside",
        "The leaves are bleached and dry from excessive sunlight",
        "My plant gets harsh afternoon sunlight and the leaves are burning",
        "There are brown dry patches caused by direct sun",
        "The leaves look scorched after several hours of strong sunlight",
        "My plant was exposed to intense sunlight and got damaged",
        "The leaf surface looks burned",
        "The leaves have pale areas that later turned brown",
        "Direct sunlight is too strong for my plant",
        "The plant has heat and sun damage on exposed leaves",
        "The leaves are developing brown patches after sunny days",
        "My plant looks burned by the sun",
        "There are crispy brown spots where the sun hits the leaves",
        "The plant was placed in full sun and now the leaves are damaged",
        "Excessive sunlight has bleached the foliage",
        "The leaves are scorched after exposure to strong sunlight",
        "My plant cannot handle the intense direct sun",
        "The sunny side of the plant has brown burned patches",
        "The leaves became damaged after moving closer to the window",
        "My plant has sunburn from strong afternoon light",
        "The foliage has bleached patches from too much light",
        "The leaves are burned because of excessive direct sunlight",
        "Strong sun is causing brown scorched spots"
    ],


    # ========================================================
    # LOW HUMIDITY
    # ========================================================

    "low_humidity": [

        "The leaf edges are dry and crispy",
        "My plant has brown crispy tips because the air is dry",
        "The room air feels very dry and the leaves are drying at the edges",
        "The leaves have dry brown tips",
        "My plant needs more humidity",
        "The leaf edges are turning brown and crispy",
        "Dry indoor air is affecting my plant",
        "The leaves are curling and becoming crispy around the edges",
        "The plant is near a heater and the air is very dry",
        "My plant has dry leaf tips despite regular watering",
        "The edges of the leaves are dry but the soil is not dry",
        "The air around the plant lacks moisture",
        "The leaves are becoming crispy due to dry air",
        "My tropical plant is suffering from low humidity",
        "The leaf margins are dry and brown",
        "The room is dry and my plant leaves are curling",
        "The plant has brown tips even though I water it properly",
        "The leaves feel dry because of low humidity",
        "Dry air is causing the foliage to become crispy",
        "The plant is near an air conditioner and the leaves are drying",
        "My plant has crispy leaf edges",
        "The humidity around my plant is very low",
        "The leaves are drying from the edges inward",
        "My indoor air is dry and the plant looks stressed",
        "The leaf tips are brown and brittle",
        "The plant needs a more humid environment",
        "The foliage has dry crispy margins",
        "The soil is moist but the leaf edges are dry",
        "The leaves are curling because the air is too dry",
        "My plant suffers during dry winter air",
        "There are brown tips caused by dry air",
        "The plant looks dry even though it is watered",
        "Low humidity may be damaging the leaves",
        "The air around the plant is too dry",
        "My leaves have dry edges and brown tips"
    ],


    # ========================================================
    # TRANSPLANT STRESS
    # ========================================================

    "transplant_stress": [

        "My plant started wilting after repotting",
        "The leaves are drooping since I moved the plant to a new pot",
        "My plant looks weak after being transplanted",
        "The plant is stressed after changing pots",
        "I recently repotted my plant and now the leaves are drooping",
        "My plant is struggling after transplanting",
        "The plant stopped growing after I moved it to another pot",
        "The leaves started yellowing after repotting",
        "My plant looks stressed since I changed the soil",
        "The plant became weak after moving it",
        "I transplanted the plant recently and it is now wilting",
        "The plant is drooping after being moved to a new container",
        "My plant has not adjusted after repotting",
        "The leaves look weak after transplanting",
        "The plant is stressed because its roots were disturbed during repotting",
        "My plant looks unhappy after changing pots",
        "Growth slowed after I transplanted the plant",
        "The plant started drooping after I replaced the soil",
        "I moved my plant to a bigger pot and now it looks stressed",
        "The leaves became weak after repotting",
        "My plant is adjusting poorly to its new pot",
        "The plant was healthy before I transplanted it",
        "The plant started wilting after I disturbed the roots",
        "My plant looks shocked after repotting",
        "The leaves are drooping because I recently moved the plant",
        "The plant is stressed after being transferred to another container",
        "My plant has not recovered since repotting",
        "The plant looks weak after a recent transplant",
        "I changed the pot and now the plant is struggling",
        "My plant became droopy after moving it to fresh soil",
        "The plant is experiencing stress after repotting",
        "The leaves changed after I transplanted the plant",
        "My plant is wilting after changing containers",
        "The plant looks shocked after being moved",
        "Repotting seems to have stressed my plant"
    ],


    # ========================================================
    # POOR DRAINAGE
    # ========================================================

    "poor_drainage": [

        "Water stays in the pot for a very long time",
        "The soil takes too long to dry after watering",
        "My pot does not seem to drain properly",
        "Water collects at the bottom of the container",
        "The soil is compacted and holds too much water",
        "There is no drainage hole in my pot",
        "The potting soil stays wet for many days",
        "Water is trapped in the bottom of the pot",
        "My plant container has poor drainage",
        "The soil feels dense and does not drain well",
        "Water remains around the roots after watering",
        "The pot is always heavy with water",
        "My plant sits in water because the container drains slowly",
        "The soil becomes muddy after watering",
        "The drainage holes appear blocked",
        "Excess water does not leave the pot",
        "The container does not allow water to escape",
        "The soil is compact and stays soaked",
        "Water pools at the bottom of the planter",
        "My pot has drainage problems",
        "The soil remains wet because water cannot drain",
        "The container has no proper drainage system",
        "Water accumulates in the pot after watering",
        "The soil is waterlogged because of poor drainage",
        "The pot takes days to drain and dry",
        "My plant may be suffering because the soil drains poorly",
        "The pot does not have enough drainage holes",
        "The soil is too dense and holds water",
        "Excess water stays around the root area",
        "The bottom of the pot remains wet",
        "My plant container drains very slowly",
        "Water cannot escape properly from the soil",
        "The potting mix stays soaked for too long",
        "There is standing water inside the planter",
        "The plant soil has poor drainage"
    ],


    # ========================================================
    # PHYSICAL DAMAGE
    # ========================================================

    "physical_damage": [

        "A stem of my plant is broken",
        "The leaves were torn accidentally",
        "My plant was damaged when it fell over",
        "Someone accidentally broke part of the plant",
        "The stem snapped",
        "The leaves have physical tears",
        "My plant was damaged during handling",
        "A branch broke accidentally",
        "The plant was knocked over and damaged",
        "Some leaves were torn",
        "The stem was bent and broken",
        "My plant has damage from being moved",
        "A part of the plant was accidentally crushed",
        "The leaves are damaged because something hit the plant",
        "My plant fell and some stems broke",
        "The plant has visible physical damage",
        "A branch has snapped off",
        "The leaves were ripped",
        "My plant was damaged by an accident",
        "The stem is broken after the pot fell",
        "The plant has been physically injured",
        "Some foliage was torn during transportation",
        "The leaves have tears from handling",
        "A stem was accidentally bent too much",
        "My plant was bumped and damaged",
        "Part of the plant broke off",
        "The plant was knocked over by accident",
        "The leaves are torn but there are no pests",
        "My plant has broken stems from physical damage",
        "The foliage was damaged during moving",
        "The plant was crushed slightly",
        "A stem broke while I was handling the plant",
        "The leaves were damaged by physical contact",
        "My plant has torn leaves from an accident",
        "The plant suffered mechanical damage"
    ],


    # ========================================================
    # DORMANCY
    # ========================================================

    "dormancy": [

        "My plant has stopped growing during winter",
        "The plant is growing very slowly because it is dormant",
        "Growth has paused during the cold season",
        "My plant looks healthy but is not producing new growth",
        "The plant is resting during winter",
        "There is little growth during the colder months",
        "My plant grows much slower in winter",
        "The plant has entered a natural resting period",
        "Growth has temporarily stopped because of the season",
        "My plant is not growing but otherwise looks healthy",
        "The plant is resting and producing fewer leaves",
        "Growth slows down naturally during winter",
        "My plant has reduced growth during the dormant season",
        "The plant is alive but not actively growing",
        "There is no new growth because the plant is dormant",
        "My plant is resting during the colder season",
        "The plant grows less during winter months",
        "Growth has slowed because of seasonal dormancy",
        "My plant looks fine but has stopped growing temporarily",
        "The plant is in a resting phase",
        "There is little activity during the dormant period",
        "My plant is healthy but not growing much in winter",
        "The plant has naturally slowed its growth",
        "The growth pause seems seasonal",
        "My plant is dormant during this time of year",
        "The plant is resting rather than actively growing",
        "New growth has slowed during the winter season",
        "The plant appears healthy despite slow growth",
        "My plant has a seasonal growth slowdown",
        "The plant is temporarily inactive",
        "Growth will likely resume in the active season",
        "The plant has entered a period of reduced growth",
        "My plant is resting and not showing many new leaves",
        "The plant is experiencing normal seasonal dormancy",
        "There is slow growth but no major visible problem"
    ]
}


# ============================================================
# CONVERT DICTIONARY INTO DATAFRAME
# ============================================================

rows = []

for problem, descriptions in problem_data.items():

    for description in descriptions:

        rows.append({

            "description": description,

            "problem": problem

        })


problem_df = pd.DataFrame(rows)


# ============================================================
# DISPLAY DATASET INFORMATION
# ============================================================

print("Total examples:", len(problem_df))

print("\nProblem category distribution:")

print(
    problem_df["problem"].value_counts()
)


# ============================================================
# CHECK DATASET
# ============================================================

print("\nMissing values:")

print(
    problem_df.isnull().sum()
)


print("\nDuplicate rows:")

print(
    problem_df.duplicated().sum()
)


# ============================================================
# DISPLAY SAMPLE DATA
# ============================================================

problem_df.sample(
    10,
    random_state=42
)

Total examples: 525

Problem category distribution:
problem
overwatering           35
underwatering          35
low_light              35
nutrient_deficiency    35
pest_problem           35
fungal_disease         35
temperature_stress     35
healthy                35
root_rot               35
sunburn                35
low_humidity           35
transplant_stress      35
poor_drainage          35
physical_damage        35
dormancy               35
Name: count, dtype: int64

Missing values:
description    0
problem        0
dtype: int64

Duplicate rows:
0

                                           description              problem
310             The roots smell bad and look unhealthy             root_rot
390         My plant is struggling after transplanting    transplant_stress
6    My plant looks unhealthy because I give it too...         overwatering
184      Dark patches are spreading across the foliage       fungal_disease
78                The stems are becoming long and weak            low_light
407  The plant started wilting after I disturbed th...    transplant_stress
524  There is slow growth but no major visible problem             dormancy
487        The leaves were damaged by physical contact      physical_damage
117                     The plant has small new leaves  nutrient_deficiency
137             The growth is weak and leaves are pale  nutrient_deficiency

# Step 1: Save the Plant Problem Dataset

In [32]:
# ============================================================
# SAVE IMPROVED DATASET
# ============================================================

problem_df.to_csv(
    r"C:\Users\mangl\OneDrive\Desktop\Plant care system\data\plant_problem_dataset.csv",
    index=False
)

print("Improved dataset saved successfully!")

Improved dataset saved successfully!

In [3]:
# Load the saved dataset

df = pd.read_csv(
    "plant_problem_dataset.csv"
)

# Display first 5 rows

df.head()

                                         description       problem
0  The leaves are turning yellow and the soil is ...  overwatering
1  My plant looks weak and the soil stays wet for...  overwatering
2           Leaves are falling and the soil is soggy  overwatering
3  I water my plant every day and now the leaves ...  overwatering
4  The plant is drooping even though I water it r...  overwatering

# Step 2: Verify the Dataset

In [4]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nProblem categories:")
print(df["problem"].unique())

print("\nNumber of categories:")
print(df["problem"].nunique())

print("\nMissing values:")
print(df.isnull().sum())

Dataset shape: (525, 2)

Columns:
Index(['description', 'problem'], dtype='str')

Problem categories:
<ArrowStringArray>
[       'overwatering',       'underwatering',           'low_light',
 'nutrient_deficiency',        'pest_problem',      'fungal_disease',
  'temperature_stress',             'healthy',            'root_rot',
             'sunburn',        'low_humidity',   'transplant_stress',
       'poor_drainage',     'physical_damage',            'dormancy']
Length: 15, dtype: str

Number of categories:
15

Missing values:
description    0
problem        0
dtype: int64

# Text Preprocessing

In this step, we clean the plant problem descriptions.

This helps make the text more consistent before converting it into numerical features.

In [5]:
import re

def clean_text(text):

    # Convert text to lowercase
    text = text.lower()

    # Remove special characters and punctuation
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [6]:
# Create a cleaned version of the descriptions

problem_df["clean_description"] = problem_df["description"].apply(
    clean_text
)


# Display original and cleaned text

problem_df[
    ["description", "clean_description", "problem"]
].head(10)

,description,clean_description,problem
0,The leaves are turning yellow and the soil is ...,the leaves are turning yellow and the soil is ...,overwatering
1,My plant looks weak and the soil stays wet for...,my plant looks weak and the soil stays wet for...,overwatering
2,Leaves are falling and the soil is soggy,leaves are falling and the soil is soggy,overwatering
3,I water my plant every day and now the leaves ...,i water my plant every day and now the leaves ...,overwatering
4,The plant is drooping even though I water it r...,the plant is drooping even though i water it r...,overwatering
5,The potting soil remains wet for a long time,the potting soil remains wet for a long time,overwatering
6,My plant looks unhealthy because I give it too...,my plant looks unhealthy because i give it too...,overwatering
7,The soil is always soggy,the soil is always soggy,overwatering
8,Yellow leaves are falling from my plant,yellow leaves are falling from my plant,overwatering
9,I think I have watered my plant too much,i think i have watered my plant too much,overwatering

## check the cleaned data

In [7]:
problem_df.sample(
    10,
    random_state=42
)[
    [
        "description",
        "clean_description",
        "problem"
    ]
]

,description,clean_description,problem
310,The roots smell bad and look unhealthy,the roots smell bad and look unhealthy,root_rot
390,My plant is struggling after transplanting,my plant is struggling after transplanting,transplant_stress
6,My plant looks unhealthy because I give it too...,my plant looks unhealthy because i give it too...,overwatering
184,Dark patches are spreading across the foliage,dark patches are spreading across the foliage,fungal_disease
78,The stems are becoming long and weak,the stems are becoming long and weak,low_light
407,The plant started wilting after I disturbed th...,the plant started wilting after i disturbed th...,transplant_stress
524,There is slow growth but no major visible problem,there is slow growth but no major visible problem,dormancy
487,The leaves were damaged by physical contact,the leaves were damaged by physical contact,physical_damage
117,The plant has small new leaves,the plant has small new leaves,nutrient_deficiency
137,The growth is weak and leaves are pale,the growth is weak and leaves are pale,nutrient_deficiency

## remove duplicates

In [8]:
print(
    "Duplicate cleaned descriptions:",
    problem_df["clean_description"].duplicated().sum()
)

Duplicate cleaned descriptions: 0

# Step 3: Prepare Data for Machine Learning

In [9]:
# ============================================================
# PREPARE INPUT AND OUTPUT DATA
# ============================================================

# Plant problem descriptions

X = df["description"]


# Problem categories

y = df["problem"]


print("Input examples:", len(X))

print("Output labels:", len(y))

Input examples: 525
Output labels: 525

# Step 4: Split the Dataset into Training and Testing Data

In [10]:
from sklearn.model_selection import train_test_split


# ============================================================
# SPLIT THE DATASET
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)


print("Training examples:", len(X_train))

print("Testing examples:", len(X_test))

Training examples: 420
Testing examples: 105

# Step 6: Improve Training Data

In this step, we improve the model's ability to understand different ways users may describe the same plant problem.

Only the training data is augmented.

The testing data remains unchanged so that the final evaluation remains fair.

In [11]:
import pandas as pd
import random

# Set random seed for reproducible results

random.seed(42)


# ============================================================
# FUNCTION TO CREATE NATURAL LANGUAGE VARIATIONS
# ============================================================

def augment_description(text):

    variations = [text]

    # Possible natural prefixes users may use

    prefixes = [

        "My plant has this problem: ",

        "Can you help? ",

        "I noticed that ",

        "Please help, ",

        "I think something is wrong because ",

        "What could be wrong? ",

        "Recently, "

    ]


    # Choose one random prefix

    prefix = random.choice(prefixes)


    # Create augmented version

    augmented_text = prefix + text.lower()


    variations.append(augmented_text)


    return variations


# ============================================================
# AUGMENT TRAINING DATA ONLY
# ============================================================

augmented_X = []

augmented_y = []


for text, label in zip(X_train, y_train):

    # Create variations for each training example

    variations = augment_description(text)


    for variation in variations:

        augmented_X.append(variation)

        augmented_y.append(label)


# ============================================================
# CONVERT BACK TO PANDAS SERIES
# ============================================================

X_train_augmented = pd.Series(augmented_X)

y_train_augmented = pd.Series(augmented_y)


# ============================================================
# DISPLAY RESULTS
# ============================================================

print("Original training examples:", len(X_train))

print("Augmented training examples:", len(X_train_augmented))

print("\nTesting examples remain unchanged:", len(X_test))


# Display a few augmented examples

augmentation_preview = pd.DataFrame({

    "description": X_train_augmented[:10],

    "problem": y_train_augmented[:10]

})


augmentation_preview

Original training examples: 420
Augmented training examples: 840

Testing examples remain unchanged: 105

                                         description              problem
0  The plant has pale bleached areas from intense...              sunburn
1  What could be wrong? the plant has pale bleach...              sunburn
2  There are yellow patches on otherwise healthy ...  nutrient_deficiency
3  My plant has this problem: there are yellow pa...  nutrient_deficiency
4  The plant looks damaged after a sudden cold spell   temperature_stress
5  My plant has this problem: the plant looks dam...   temperature_stress
6              The soil becomes muddy after watering        poor_drainage
7  What could be wrong? the soil becomes muddy af...        poor_drainage
8            White powder is appearing on the leaves       fungal_disease
9  I noticed that white powder is appearing on th...       fungal_disease

# Step 7: TF-IDF Vectorization

In this step, we convert the plant problem descriptions from text into numerical features.

We fit the TF-IDF vectorizer only on the augmented training data.

The same fitted vectorizer is then used to transform the test data.

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer


# ============================================================
# CREATE TF-IDF VECTORIZER
# ============================================================

tfidf_vectorizer = TfidfVectorizer(

    # Use individual words and two-word combinations
    ngram_range=(1, 2),

    # Keep words appearing at least once
    min_df=1,

    # Apply logarithmic scaling
    sublinear_tf=True,

    # Remove common English words
    stop_words="english"
)


# ============================================================
# FIT AND TRANSFORM AUGMENTED TRAINING DATA
# ============================================================

X_train_tfidf = tfidf_vectorizer.fit_transform(
    X_train_augmented
)


# ============================================================
# TRANSFORM TEST DATA
# ============================================================

X_test_tfidf = tfidf_vectorizer.transform(
    X_test
)


# ============================================================
# DISPLAY INFORMATION
# ============================================================

print(
    "Training feature matrix shape:",
    X_train_tfidf.shape
)

print(
    "\nTesting feature matrix shape:",
    X_test_tfidf.shape
)

print(
    "\nNumber of features:",
    len(tfidf_vectorizer.get_feature_names_out())
)

Training feature matrix shape: (840, 1502)

Testing feature matrix shape: (105, 1502)

Number of features: 1502

# Step 7: Train the Logistic Regression Model

In this step, we train a Logistic Regression model using the TF-IDF features.

The model will learn to classify plant problem descriptions into one of the 15 problem categories.

In [19]:
from sklearn.linear_model import LogisticRegression


# Create the model

problem_model = LogisticRegression(
    max_iter=3000,
    class_weight="balanced",
    random_state=42
)


# Train the model
problem_model.fit(
    X_train_tfidf,
    y_train_augmented

)


print("Model training completed successfully!")

Model training completed successfully!

# Step 8: Evaluate the Model

In this step, we evaluate the trained Logistic Regression model using
the testing dataset.

We will calculate the accuracy of the model and examine its detailed
classification performance.

In [20]:
# ============================================================
# STEP 8: MODEL EVALUATION
# ============================================================

from sklearn.metrics import classification_report, accuracy_score


# Make predictions on the testing data

y_pred = problem_model.predict(
    X_test_tfidf
)


# Calculate accuracy

accuracy = accuracy_score(
    y_test,
    y_pred
)


print(
    "Model Accuracy:",
    round(accuracy * 100, 2),
    "%"
)


# Display detailed evaluation report

print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred
    )
)

Model Accuracy: 80.95 %

Classification Report:

                     precision    recall  f1-score   support

           dormancy       0.88      1.00      0.93         7
     fungal_disease       1.00      0.86      0.92         7
            healthy       0.67      0.86      0.75         7
       low_humidity       0.78      1.00      0.88         7
          low_light       0.80      0.57      0.67         7
nutrient_deficiency       0.83      0.71      0.77         7
       overwatering       0.50      0.71      0.59         7
       pest_problem       0.86      0.86      0.86         7
    physical_damage       0.78      1.00      0.88         7
      poor_drainage       0.83      0.71      0.77         7
           root_rot       1.00      0.86      0.92         7
            sunburn       0.88      1.00      0.93         7
 temperature_stress       1.00      0.71      0.83         7
  transplant_stress       1.00      0.71      0.83         7
      underwatering       0.67      0.57      0.62         7

           accuracy                           0.81       105
          macro avg       0.83      0.81      0.81       105
       weighted avg       0.83      0.81      0.81       105

# Step 9: Test the Model with Custom User Inputs

In this step, we test the trained model using new sentences.

These sentences should not be copied directly from the training dataset.

This helps us check whether the model can understand
natural language descriptions written by users.

In [21]:
# ============================================================
# TEST THE MODEL WITH CUSTOM USER INPUTS
# ============================================================

test_sentences = [

    "I watered my plant too much and now the leaves are yellow",

    "My plant has not received water for several days and the soil is dry",

    "There are tiny bugs crawling underneath the leaves",

    "My plant stopped growing during the winter season",

    "The leaves have brown burned areas because of strong sunlight",

    "My plant started wilting after I changed its pot",

    "The roots are soft, black and smell bad",

    "The leaves are green and the plant is growing properly"
]


# Clean the test sentences

cleaned_test_sentences = [

    clean_text(sentence)

    for sentence in test_sentences
]


# Convert sentences into TF-IDF features

test_tfidf = tfidf_vectorizer.transform(
    cleaned_test_sentences
)


# Make predictions

predictions = problem_model.predict(
    test_tfidf
)


# Display results

for sentence, prediction in zip(
    test_sentences,
    predictions
):

    print("User Input:")

    print(sentence)

    print("Predicted Problem:")

    print(prediction)

    print("-" * 60)

User Input:
I watered my plant too much and now the leaves are yellow
Predicted Problem:
overwatering
------------------------------------------------------------
User Input:
My plant has not received water for several days and the soil is dry
Predicted Problem:
underwatering
------------------------------------------------------------
User Input:
There are tiny bugs crawling underneath the leaves
Predicted Problem:
pest_problem
------------------------------------------------------------
User Input:
My plant stopped growing during the winter season
Predicted Problem:
dormancy
------------------------------------------------------------
User Input:
The leaves have brown burned areas because of strong sunlight
Predicted Problem:
sunburn
------------------------------------------------------------
User Input:
My plant started wilting after I changed its pot
Predicted Problem:
transplant_stress
------------------------------------------------------------
User Input:
The roots are soft, black and smell bad
Predicted Problem:
root_rot
------------------------------------------------------------
User Input:
The leaves are green and the plant is growing properly
Predicted Problem:
healthy
------------------------------------------------------------

# Step 9: Test Model Predictions with Confidence

In this step, we test the trained model with new plant problem descriptions.

The model predicts:

1. The most likely plant problem.
2. The confidence percentage for that prediction.

In [22]:
# ============================================================
# STEP 9: PREDICTION WITH CONFIDENCE SCORE
# ============================================================


# Example user sentences

test_sentences = [

    "I watered my plant too much and now the leaves are yellow",

    "My plant has not received water for several days and the soil is dry",

    "There are tiny bugs crawling underneath the leaves",

    "My plant stopped growing during the winter season",

    "The leaves have brown burned areas because of strong sunlight",

    "My plant started wilting after I changed its pot",

    "The roots are soft, black and smell bad",

    "The leaves are green and the plant is growing properly"

]


# ============================================================
# CLEAN THE USER SENTENCES
# ============================================================

cleaned_test_sentences = [

    clean_text(sentence)

    for sentence in test_sentences

]


# ============================================================
# CONVERT TEXT TO TF-IDF FEATURES
# ============================================================

test_tfidf = tfidf_vectorizer.transform(
    cleaned_test_sentences
)


# ============================================================
# PREDICT PROBLEMS
# ============================================================

predictions = problem_model.predict(
    test_tfidf
)


# ============================================================
# GET CONFIDENCE PROBABILITIES
# ============================================================

probabilities = problem_model.predict_proba(
    test_tfidf
)


# Get highest probability for each prediction

confidence_scores = probabilities.max(
    axis=1
) * 100


# ============================================================
# DISPLAY RESULTS
# ============================================================

for sentence, prediction, confidence in zip(

    test_sentences,

    predictions,

    confidence_scores

):

    print("User Input:")

    print(sentence)


    print("\nPredicted Problem:")

    print(prediction)


    print("\nConfidence:")

    print(f"{confidence:.2f}%")


    print("-" * 60)

User Input:
I watered my plant too much and now the leaves are yellow

Predicted Problem:
overwatering

Confidence:
34.88%
------------------------------------------------------------
User Input:
My plant has not received water for several days and the soil is dry

Predicted Problem:
underwatering

Confidence:
50.46%
------------------------------------------------------------
User Input:
There are tiny bugs crawling underneath the leaves

Predicted Problem:
pest_problem

Confidence:
53.98%
------------------------------------------------------------
User Input:
My plant stopped growing during the winter season

Predicted Problem:
dormancy

Confidence:
57.55%
------------------------------------------------------------
User Input:
The leaves have brown burned areas because of strong sunlight

Predicted Problem:
sunburn

Confidence:
74.34%
------------------------------------------------------------
User Input:
My plant started wilting after I changed its pot

Predicted Problem:
transplant_stress

Confidence:
44.00%
------------------------------------------------------------
User Input:
The roots are soft, black and smell bad

Predicted Problem:
root_rot

Confidence:
58.68%
------------------------------------------------------------
User Input:
The leaves are green and the plant is growing properly

Predicted Problem:
healthy

Confidence:
59.39%
------------------------------------------------------------

# Step 11: Create a Plant Problem Prediction Function

This function accepts a user's description of a plant problem.

It cleans the text, converts it into TF-IDF features, predicts
the plant problem, and calculates the confidence score.

In [24]:
# ============================================================
# STEP 11: CREATE PREDICTION FUNCTION
# ============================================================

def predict_plant_problem(user_description):


    # ========================================================
    # CLEAN USER INPUT
    # ========================================================

    cleaned_description = clean_text(
        user_description
    )


    # ========================================================
    # CONVERT TEXT TO TF-IDF FEATURES
    # ========================================================

    description_tfidf = tfidf_vectorizer.transform(
        [cleaned_description]
    )


    # ========================================================
    # PREDICT PROBLEM
    # ========================================================

    prediction = problem_model.predict(
        description_tfidf
    )[0]


    # ========================================================
    # GET CONFIDENCE SCORE
    # ========================================================

    probabilities = problem_model.predict_proba(
        description_tfidf
    )[0]


    confidence = (
        max(probabilities) * 100
    )


    # ========================================================
    # RETURN RESULTS
    # ========================================================

    return {

        "problem": prediction,

        "confidence": round(
            confidence,
            2
        )

    }

In [25]:
# ============================================================
# TEST THE PREDICTION FUNCTION
# ============================================================

test_description = (
    "My plant has yellow leaves and the soil is always wet"
)


result = predict_plant_problem(
    test_description
)


print("Predicted Problem:")

print(
    result["problem"]
)


print("\nConfidence:")

print(
    result["confidence"],
    "%"
)

Predicted Problem:
overwatering

Confidence:
66.92 %

# Step 12: Add Causes and Recommendations

In this step, we create possible causes and recommendations
for each plant problem category.

These details will be combined with the machine learning
model prediction to provide useful advice to the user.

In [26]:
# ============================================================
# STEP 12: PLANT PROBLEM INFORMATION
# ============================================================


problem_information = {


    # ========================================================
    # OVERWATERING
    # ========================================================

    "overwatering": {

        "cause": (
            "The plant may be receiving water too frequently, "
            "causing the soil to remain excessively wet."
        ),

        "recommendation": (
            "Allow the soil to dry before watering again. "
            "Check that the pot has proper drainage and avoid "
            "watering on a fixed schedule without checking the soil."
        )
    },


    # ========================================================
    # UNDERWATERING
    # ========================================================

    "underwatering": {

        "cause": (
            "The plant may not be receiving enough water, "
            "causing the soil and plant tissues to become too dry."
        ),

        "recommendation": (
            "Water the plant thoroughly when appropriate and "
            "check the soil regularly. Adjust the watering routine "
            "according to the plant's needs."
        )
    },


    # ========================================================
    # LOW LIGHT
    # ========================================================

    "low_light": {

        "cause": (
            "The plant may not be receiving enough suitable light "
            "for healthy growth."
        ),

        "recommendation": (
            "Move the plant to a brighter location suitable for "
            "its species. Avoid suddenly exposing a shade-loving "
            "plant to intense direct sunlight."
        )
    },


    # ========================================================
    # NUTRIENT DEFICIENCY
    # ========================================================

    "nutrient_deficiency": {

        "cause": (
            "The plant may not have sufficient nutrients available "
            "for healthy growth."
        ),

        "recommendation": (
            "Check whether the plant needs fresh growing medium or "
            "appropriate fertilizer. Follow the care requirements "
            "for the specific plant species."
        )
    },


    # ========================================================
    # PEST PROBLEM
    # ========================================================

    "pest_problem": {

        "cause": (
            "The plant may be affected by insects or other pests "
            "that are damaging its leaves or stems."
        ),

        "recommendation": (
            "Inspect the leaves, especially their undersides. "
            "Isolate heavily affected plants if necessary and use "
            "an appropriate plant-safe pest treatment."
        )
    },


    # ========================================================
    # FUNGAL DISEASE
    # ========================================================

    "fungal_disease": {

        "cause": (
            "The plant may have a fungal infection, which can be "
            "encouraged by excess moisture or poor air circulation."
        ),

        "recommendation": (
            "Remove heavily affected plant material where appropriate, "
            "avoid unnecessarily wet foliage, and improve air "
            "circulation. Consider suitable treatment if needed."
        )
    },


    # ========================================================
    # TEMPERATURE STRESS
    # ========================================================

    "temperature_stress": {

        "cause": (
            "The plant may have been exposed to temperatures that "
            "are too hot, too cold, or changing too rapidly."
        ),

        "recommendation": (
            "Move the plant away from extreme heat, cold drafts, "
            "heaters, or air conditioners. Keep the temperature "
            "within a range suitable for the plant."
        )
    },


    # ========================================================
    # HEALTHY
    # ========================================================

    "healthy": {

        "cause": (
            "No significant problem is indicated by the description."
        ),

        "recommendation": (
            "Continue providing suitable water, light, temperature, "
            "and regular care for the plant."
        )
    },


    # ========================================================
    # ROOT ROT
    # ========================================================

    "root_rot": {

        "cause": (
            "The roots may have been damaged by prolonged excess "
            "moisture and lack of oxygen in the growing medium."
        ),

        "recommendation": (
            "Check the root system and remove severely damaged roots "
            "where appropriate. Use fresh, well-draining growing "
            "medium and avoid keeping the roots constantly wet."
        )
    },


    # ========================================================
    # SUNBURN
    # ========================================================

    "sunburn": {

        "cause": (
            "The plant may have been exposed to sunlight that is "
            "too intense for its leaves."
        ),

        "recommendation": (
            "Move the plant to a location with more suitable light. "
            "Introduce stronger sunlight gradually when appropriate."
        )
    },


    # ========================================================
    # LOW HUMIDITY
    # ========================================================

    "low_humidity": {

        "cause": (
            "The surrounding air may be too dry for the plant."
        ),

        "recommendation": (
            "Provide a more suitable humidity level for the plant "
            "and keep it away from sources of very dry air when possible."
        )
    },


    # ========================================================
    # TRANSPLANT STRESS
    # ========================================================

    "transplant_stress": {

        "cause": (
            "The plant may be adjusting to changes in its roots, "
            "soil, or growing environment after transplanting."
        ),

        "recommendation": (
            "Give the plant time to adjust and provide stable care. "
            "Avoid unnecessary disturbance of the roots and sudden "
            "environmental changes."
        )
    },


    # ========================================================
    # POOR DRAINAGE
    # ========================================================

    "poor_drainage": {

        "cause": (
            "Water may not be draining properly from the pot or "
            "growing medium."
        ),

        "recommendation": (
            "Use a container with suitable drainage and a "
            "well-draining growing medium. Check that drainage "
            "holes are not blocked."
        )
    },


    # ========================================================
    # PHYSICAL DAMAGE
    # ========================================================

    "physical_damage": {

        "cause": (
            "The plant may have been damaged by impact, handling, "
            "bending, or another physical accident."
        ),

        "recommendation": (
            "Remove severely damaged plant parts where appropriate "
            "and provide stable conditions for recovery. Handle "
            "the plant carefully."
        )
    },


    # ========================================================
    # DORMANCY
    # ========================================================

    "dormancy": {

        "cause": (
            "The plant may be experiencing a natural period of "
            "reduced growth because of seasonal conditions."
        ),

        "recommendation": (
            "Continue providing appropriate basic care, but avoid "
            "forcing excessive growth. Adjust watering and care "
            "according to the plant's dormant-season needs."
        )
    }

}


print(
    "Plant problem information created successfully!"
)


print(
    "\nTotal categories:",
    len(problem_information)
)

Plant problem information created successfully!

Total categories: 15

# Step 13: Complete Plant Problem Prediction Function

This function accepts a user's plant problem description and returns:

- Predicted plant problem
- Confidence score
- Possible cause
- Recommendation

In [28]:
# ============================================================
# STEP 13: COMPLETE PREDICTION FUNCTION
# ============================================================

def predict_plant_problem(user_description):


    # ========================================================
    # CLEAN USER INPUT
    # ========================================================

    cleaned_description = clean_text(
        user_description
    )


    # ========================================================
    # CONVERT TEXT TO TF-IDF FEATURES
    # ========================================================

    description_tfidf = tfidf_vectorizer.transform(
        [cleaned_description]
    )


    # ========================================================
    # PREDICT PLANT PROBLEM
    # ========================================================

    prediction = problem_model.predict(
        description_tfidf
    )[0]


    # ========================================================
    # GET CONFIDENCE SCORE
    # ========================================================

    probabilities = problem_model.predict_proba(
        description_tfidf
    )[0]


    confidence = (
        max(probabilities) * 100
    )


    # ========================================================
    # GET PROBLEM INFORMATION
    # ========================================================

    problem_details = problem_information.get(
        prediction,
        {}
    )


    # ========================================================
    # GET CAUSE
    # ========================================================

    cause = problem_details.get(
        "cause",
        "Cause information is not available."
    )


    # ========================================================
    # GET RECOMMENDATION
    # ========================================================

    recommendation = problem_details.get(
        "recommendation",
        "Recommendation information is not available."
    )


    # ========================================================
    # RETURN COMPLETE RESULT
    # ========================================================

    return {

        "problem": prediction,

        "confidence": round(
            confidence,
            2
        ),

        "cause": cause,

        "recommendation": recommendation
    }

In [29]:
# ============================================================
# TEST COMPLETE PREDICTION FUNCTION
# ============================================================

test_description = (
    "My plant has yellow leaves and the soil remains wet for many days"
)


result = predict_plant_problem(
    test_description
)


print("Predicted Problem:")

print(
    result["problem"]
)


print("\nConfidence:")

print(
    result["confidence"],
    "%"
)


print("\nPossible Cause:")

print(
    result["cause"]
)


print("\nRecommendation:")

print(
    result["recommendation"]
)

Predicted Problem:
overwatering

Confidence:
44.91 %

Possible Cause:
The plant may be receiving water too frequently, causing the soil to remain excessively wet.

Recommendation:
Allow the soil to dry before watering again. Check that the pot has proper drainage and avoid watering on a fixed schedule without checking the soil.

# Step 14: Save the Trained Model

In this step, we save:

- The trained Logistic Regression model
- The TF-IDF vectorizer

These files will later be loaded by the Flask website.

In [31]:
# ============================================================
# STEP 14: SAVE MODEL AND VECTORIZER
# ============================================================

import joblib


# ============================================================
# SAVE TRAINED PLANT PROBLEM MODEL
# ============================================================

joblib.dump(
    problem_model,
    r"C:\Users\mangl\OneDrive\Desktop\Plant care system\model\plant_problem_model.pkl"
)


# ============================================================
# SAVE TF-IDF VECTORIZER
# ============================================================

joblib.dump(
    tfidf_vectorizer,
    r"C:\Users\mangl\OneDrive\Desktop\Plant care system\model\plant_problem_vectorizer.pkl"
)


# ============================================================
# CONFIRM SUCCESS
# ============================================================

print("Plant problem model saved successfully!")

print("TF-IDF vectorizer saved successfully!")

Plant problem model saved successfully!
TF-IDF vectorizer saved successfully!